#!/bin/bash

echo "Build Begin" >> /tmp/tmp.log
set +e
rm -rf tmp/memcached
mkdir tmp
set -e

set -x
exec >> /tmp/tmp.log 2>&1 
version=${MEMCACHED_TAG:-1.4.15}
binaries="../../versions/$version/bin"

#pushd tmp
#wget http://ftp.kaist.ac.kr/gnu/gnu/libtool/libtool-2.4.tar.gz
#tar -xzvf libtool-2.4.tar.gz
#
#pushd libtool-2.4
#./configure
#make
#make install
#popd

#wget https://github.com/downloads/libevent/libevent/libevent-2.0.21-stable.tar.gz
#tar -xzvf libevent-2.0.21-stable.tar.gz
#pushd libevent-2.0.21-stable
#./autogen.sh
#popd

git clone https://github.com/memcached/memcached memcached
cd memcached
git checkout $version
./autogen.sh
 
make -j 2

mkdir -p $binaries

echo $(git rev-parse $version) > $binaries/.gitcommit
for file in memcached scripts/memcached-tool; do
  cp -f $file $binaries
done

popd
rm -rf tmp/memcached
