#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "HOST=\"$OPENSHIFT_GEAR_DNS\";PORT=\"$OPENSHIFT_MEMCACHED_PROXY_PORT\";USERNAME=\"$OPENSHIFT_MEMCACHED_USERNAME\";PASSWORD=\"$OPENSHIFT_MEMCACHED_PASSWORD\""

{
echo hook-pub: `date`
for ((i=0;$#>0;i++)); do
	echo " $i: $1"
	shift
done
} >> $OPENSHIFT_DATA_DIR/hook-pub
