#!/usr/bin/env python

import os, sys

OPENSHIFT_MEMCACHED_HOST     = os.environ['OPENSHIFT_GEAR_DNS']
OPENSHIFT_MEMCACHED_PORT     = os.environ['OPENSHIFT_MEMCACHED_PROXY_PORT']
OPENSHIFT_MEMCACHED_USERNAME = os.environ['OPENSHIFT_MEMCACHED_USERNAME']
OPENSHIFT_MEMCACHED_PASSWORD = os.environ['OPENSHIFT_MEMCACHED_PASSWORD']

print 'OPENSHIFT_MEMCACHED_HOST=%s' % OPENSHIFT_MEMCACHED_HOST
print 'OPENSHIFT_MEMCACHED_PORT=%s' % OPENSHIFT_MEMCACHED_PORT
print 'OPENSHIFT_MEMCACHED_USERNAME=%s' % OPENSHIFT_MEMCACHED_USERNAME
print 'OPENSHIFT_MEMCACHED_PASSWORD=%s' % OPENSHIFT_MEMCACHED_PASSWORD

def str_to_list(name):
	v = os.environ.get('OPENSHIFT_MEMCACHED_CLUSTER_%s' % name, '')
	return v.split(',') if v else []

hosts = str_to_list('HOST')

if OPENSHIFT_MEMCACHED_HOST in hosts:
	sys.exit(0)

ports     = str_to_list('PORT')
usernames = str_to_list('USERNAME')
passwords = str_to_list('PASSWORD')

assert len(hosts) == len(ports) == len(usernames) == len(passwords)

hosts.append(OPENSHIFT_MEMCACHED_HOST)
ports.append(OPENSHIFT_MEMCACHED_PORT)
usernames.append(OPENSHIFT_MEMCACHED_USERNAME)
passwords.append(OPENSHIFT_MEMCACHED_PASSWORD)

print 'OPENSHIFT_MEMCACHED_CLUSTER_HOST=%s' % ','.join(hosts)
print 'OPENSHIFT_MEMCACHED_CLUSTER_PORT=%s' % ','.join(ports)
print 'OPENSHIFT_MEMCACHED_CLUSTER_USERNAME=%s' % ','.join(usernames)
print 'OPENSHIFT_MEMCACHED_CLUSTER_PASSWORD=%s' % ','.join(passwords)
