#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "hostname=\"$OPENSHIFT_GEAR_DNS\";port=\"$OPENSHIFT_MEMCACHED_PROXY_PORT\";username=\"$OPENSHIFT_MEMCACHED_USERNAME\";password=\"$OPENSHIFT_MEMCACHED_PASSWORD\""

{
echo hook-pub: `date`
for ((i=0;$#>0;i++)); do
	echo " $i: $1"
	shift
done
} >> $OPENSHIFT_DATA_DIR/hook-pub
